// PROPOSE phase: create GitHub issues from ideas generated by IDEATE.
// Respects max_issues_per_run and require_approval settings.

import { createClient } from './github.js';

export async function propose(context) {
  const { owner, repo, token, ideas, config, dryRun } = context;

  if (!ideas || ideas.length === 0) {
    console.log('No ideas to propose — run IDEATE first.');
    return null;
  }

  const gh = createClient(token);
  const maxIssues = config.limits?.max_issues_per_run || 3;
  const proposalLabel = config.limits?.labels?.proposal || 'roadmap-proposal';
  const agentLabel = config.limits?.labels?.agent || 'agent-generated';

  // Ensure labels exist.
  await ensureLabel(gh, owner, repo, proposalLabel, 'Issue proposed by repo-butler', '7057ff');
  await ensureLabel(gh, owner, repo, agentLabel, 'Created by an automated agent', 'c5def5');

  // Sort by priority: high > medium > low.
  const priorityOrder = { high: 0, medium: 1, low: 2 };
  const sorted = [...ideas].sort((a, b) =>
    (priorityOrder[a.priority] ?? 1) - (priorityOrder[b.priority] ?? 1)
  );

  const toPropose = sorted.slice(0, maxIssues);
  const created = [];

  for (const idea of toPropose) {
    const labels = [proposalLabel, agentLabel, ...idea.labels];
    const body = [
      idea.body,
      '',
      '---',
      `*Priority: ${idea.priority} — proposed by [repo-butler](https://github.com/IsmaelMartinez/repo-butler)*`,
    ].join('\n');

    if (dryRun) {
      console.log(`DRY RUN — would create issue: "${idea.title}" [${labels.join(', ')}]`);
      created.push({ title: idea.title, labels, url: null });
      continue;
    }

    const issue = await gh.request(`/repos/${owner}/${repo}/issues`, {
      method: 'POST',
      body: { title: idea.title, body, labels },
    });

    console.log(`Created issue #${issue.number}: ${issue.title} — ${issue.html_url}`);
    created.push({ title: idea.title, number: issue.number, labels, url: issue.html_url });
  }

  if (toPropose.length < ideas.length) {
    console.log(`Capped at ${maxIssues} issues. ${ideas.length - maxIssues} ideas dropped.`);
  }

  return { created, dropped: ideas.length - toPropose.length };
}

async function ensureLabel(gh, owner, repo, name, description, color) {
  try {
    await gh.request(`/repos/${owner}/${repo}/labels/${encodeURIComponent(name)}`);
  } catch {
    try {
      await gh.request(`/repos/${owner}/${repo}/labels`, {
        method: 'POST',
        body: { name, description, color },
      });
      console.log(`Created label: ${name}`);
    } catch {
      // Label might have been created concurrently — ignore.
    }
  }
}
