// PROPOSE phase: create GitHub issues from ideas generated by IDEATE.
// Respects max_issues_per_run and require_approval settings.

import { createClient } from './github.js';
import { validateIdeas } from './safety.js';

// Common words stripped from titles before comparison to reduce false positives.
const STOP_WORDS = new Set([
  'add', 'fix', 'update', 'implement', 'remove', 'create', 'delete',
  'the', 'a', 'an', 'to', 'for', 'in', 'of', 'and', 'or', 'is', 'with',
]);

/**
 * Jaccard similarity between two strings based on word overlap.
 * Words are lowercased and common stop words are stripped.
 * Returns a value between 0 (no overlap) and 1 (identical word sets).
 */
export function jaccardSimilarity(a, b) {
  const wordsOf = (s) => {
    const words = (s || '').toLowerCase().split(/\s+/).filter(w => w.length > 0);
    return new Set(words.filter(w => !STOP_WORDS.has(w)));
  };

  const setA = wordsOf(a);
  const setB = wordsOf(b);

  let intersection = 0;
  for (const w of setA) {
    if (setB.has(w)) intersection++;
  }

  const union = setA.size + setB.size - intersection;
  return union === 0 ? 1.0 : intersection / union;
}

/**
 * Fetch open issues and find any with titles similar to the proposed title.
 * Returns an array of { number, title, similarity } for matches above threshold.
 */
export async function findDuplicates(gh, owner, repo, title, threshold = 0.6) {
  let issues;
  try {
    issues = await gh.paginate(`/repos/${owner}/${repo}/issues`, {
      params: { state: 'open', per_page: 100 },
    });
  } catch (error) {
    // If we can't fetch issues, don't block proposal creation.
    console.warn(`Could not fetch issues for duplicate check: ${error.message}`);
    return [];
  }

  // Filter out PRs (GitHub includes them in the issues endpoint).
  const realIssues = issues.filter(i => !i.pull_request);

  const matches = [];
  for (const issue of realIssues) {
    const similarity = jaccardSimilarity(title, issue.title);
    if (similarity > threshold) {
      matches.push({ number: issue.number, title: issue.title, similarity });
    }
  }

  return matches.sort((a, b) => b.similarity - a.similarity);
}

/**
 * Build the issue body. Uses structured format when Phase 4 fields are present,
 * otherwise falls back to the plain body for backward compatibility.
 */
export function buildIssueBody(idea) {
  const hasStructuredFields = idea.rationale || idea.currentState ||
    idea.proposedState || (idea.affectedFiles?.length > 0) || idea.scope;

  if (!hasStructuredFields) {
    return [
      idea.body,
      '',
      '---',
      `*Priority: ${idea.priority} — proposed by [repo-butler](https://github.com/IsmaelMartinez/repo-butler)*`,
    ].join('\n');
  }

  const sections = [];

  if (idea.rationale) {
    sections.push(`## Rationale\n${idea.rationale}`);
  }
  if (idea.currentState) {
    sections.push(`## Current State\n${idea.currentState}`);
  }
  if (idea.proposedState) {
    sections.push(`## Proposed State\n${idea.proposedState}`);
  }
  if (idea.scope) {
    sections.push(`## Scope\n${idea.scope}`);
  }
  if (idea.affectedFiles && idea.affectedFiles.length > 0) {
    const fileList = idea.affectedFiles.map(f => `- ${f}`).join('\n');
    sections.push(`## Affected Files\n${fileList}`);
  }

  sections.push('---');
  sections.push(`*Priority: ${idea.priority} — proposed by [repo-butler](https://github.com/IsmaelMartinez/repo-butler)*`);

  return sections.join('\n\n');
}

/**
 * Check if a set of labels includes the governance-declined marker.
 * Labels can be objects with .name or plain strings.
 */
export function isGovernanceDeclined(labels) {
  if (!Array.isArray(labels)) return false;
  return labels.some(l => (l.name || l) === 'governance-declined');
}

/**
 * Find open or recently closed PRs with titles similar to the proposed title.
 * Used by governance proposals to avoid re-proposing declined changes.
 */
export async function findDuplicatePRs(gh, owner, repo, title, { threshold = 0.6, includeClosedDays = 0 } = {}) {
  const matches = [];

  // Check open PRs.
  let openPRs;
  try {
    openPRs = await gh.paginate(`/repos/${owner}/${repo}/pulls`, {
      params: { state: 'open', per_page: 100 },
    });
  } catch {
    return [];
  }

  for (const pr of openPRs) {
    const similarity = jaccardSimilarity(title, pr.title);
    if (similarity > threshold) {
      matches.push({ number: pr.number, title: pr.title, similarity, state: 'open' });
    }
  }

  // Check recently closed PRs if requested.
  // Uses sort=updated to get most recent first, capped at 100 to avoid excessive
  // API calls on repos with thousands of PRs. The date cutoff below filters further.
  if (includeClosedDays > 0) {
    let closedPRs;
    try {
      closedPRs = await gh.paginate(`/repos/${owner}/${repo}/pulls`, {
        params: { state: 'closed', sort: 'updated', direction: 'desc', per_page: 100 },
        max: 100,
      });
    } catch {
      closedPRs = [];
    }

    const cutoff = Date.now() - includeClosedDays * 86400000;
    for (const pr of closedPRs) {
      if (!pr.closed_at || new Date(pr.closed_at).getTime() < cutoff) continue;
      const similarity = jaccardSimilarity(title, pr.title);
      if (similarity > threshold) {
        matches.push({
          number: pr.number, title: pr.title, similarity,
          state: 'closed',
          declined: isGovernanceDeclined(pr.labels || []),
        });
      }
    }
  }

  return matches.sort((a, b) => b.similarity - a.similarity);
}

export async function propose(context) {
  const { owner, repo, token, ideas, config, dryRun } = context;

  if (!ideas || ideas.length === 0) {
    console.log('No ideas to propose — run IDEATE first.');
    return null;
  }

  // Safety-filter ideas before proposing.
  const safety = validateIdeas(ideas);
  if (safety.errors.length > 0) {
    console.warn(`SAFETY: ${safety.errors.length} issues found, ${ideas.length - safety.filtered.length} ideas dropped:`);
    for (const err of safety.errors) console.warn(`  - ${err}`);
  }
  if (!safety.valid) {
    console.error('SAFETY: No ideas passed validation. Skipping PROPOSE.');
    return { created: [], dropped: ideas.length, safety };
  }
  const safeIdeas = safety.filtered;

  const requireApproval = config.limits?.require_approval !== false;

  if (requireApproval && !dryRun) {
    console.log('require_approval is enabled — running in dry-run mode.');
    console.log('Set require_approval: false in .github/roadmap.yml to create issues automatically.');
    console.log('Ideas that would be proposed:');
    for (const idea of safeIdeas) {
      console.log(`  [${idea.priority}] ${idea.title}`);
    }
    return { created: [], dropped: ideas.length, require_approval: true };
  }

  const gh = createClient(token);
  const maxIssues = config.limits?.max_issues_per_run || 3;
  const proposalLabel = config.limits?.labels?.proposal || 'roadmap-proposal';
  const agentLabel = config.limits?.labels?.agent || 'agent-generated';

  // Ensure labels exist.
  await ensureLabel(gh, owner, repo, proposalLabel, 'Issue proposed by repo-butler', '7057ff');
  await ensureLabel(gh, owner, repo, agentLabel, 'Created by an automated agent', 'c5def5');

  // Sort by priority: high > medium > low.
  const priorityOrder = { high: 0, medium: 1, low: 2 };
  const sorted = [...safeIdeas].sort((a, b) =>
    (priorityOrder[a.priority] ?? 1) - (priorityOrder[b.priority] ?? 1)
  );

  const toPropose = sorted.slice(0, maxIssues);
  const created = [];
  const skippedDuplicates = [];

  for (const idea of toPropose) {
    // Duplicate detection: skip if a similar open issue already exists.
    const duplicates = await findDuplicates(gh, owner, repo, idea.title);
    if (duplicates.length > 0) {
      const best = duplicates[0];
      console.log(`Skipping '${idea.title}' — similar to existing #${best.number}: '${best.title}' (similarity: ${best.similarity.toFixed(2)})`);
      skippedDuplicates.push({ title: idea.title, duplicate: best });
      continue;
    }

    // PR duplicate detection: skip if a similar open or recently declined PR exists.
    const prDuplicates = await findDuplicatePRs(gh, owner, repo, idea.title, { includeClosedDays: 90 });
    if (prDuplicates.length > 0) {
      const best = prDuplicates[0];
      const reason = best.declined ? 'governance-declined' : `similar ${best.state} PR`;
      console.log(`Skipping '${idea.title}' — ${reason} #${best.number}: '${best.title}' (similarity: ${best.similarity.toFixed(2)})`);
      skippedDuplicates.push({ title: idea.title, duplicate: best, reason });
      continue;
    }

    const labels = [proposalLabel, agentLabel, ...idea.labels];
    const body = buildIssueBody(idea);

    if (dryRun) {
      console.log(`DRY RUN — would create issue: "${idea.title}" [${labels.join(', ')}]`);
      created.push({ title: idea.title, labels, url: null });
      continue;
    }

    const issue = await gh.request(`/repos/${owner}/${repo}/issues`, {
      method: 'POST',
      body: { title: idea.title, body, labels },
    });

    console.log(`Created issue #${issue.number}: ${issue.title} — ${issue.html_url}`);
    created.push({ title: idea.title, number: issue.number, labels, url: issue.html_url });
  }

  if (toPropose.length < safeIdeas.length) {
    console.log(`Capped at ${maxIssues} issues. ${safeIdeas.length - maxIssues} ideas dropped.`);
  }

  return { created, dropped: ideas.length - created.length, skippedDuplicates };
}

async function ensureLabel(gh, owner, repo, name, description, color) {
  try {
    await gh.request(`/repos/${owner}/${repo}/labels/${encodeURIComponent(name)}`);
  } catch {
    try {
      await gh.request(`/repos/${owner}/${repo}/labels`, {
        method: 'POST',
        body: { name, description, color },
      });
      console.log(`Created label: ${name}`);
    } catch {
      // Label might have been created concurrently — ignore.
    }
  }
}
