// PROPOSE phase: create GitHub issues from ideas generated by IDEATE.
// Respects max_issues_per_run and require_approval settings.

import { createClient, paginateIssues } from './github.js';
import { validateIdeas, validateIssueBody, sanitizeLabels, redactErrorForLog, resolveCrossRepoDestination } from './safety.js';
import { eligibleRepos } from './governance.js';

// Common words stripped from titles before comparison to reduce false positives.
const STOP_WORDS = new Set([
  'add', 'fix', 'update', 'implement', 'remove', 'create', 'delete',
  'the', 'a', 'an', 'to', 'for', 'in', 'of', 'and', 'or', 'is', 'with',
]);

/**
 * Jaccard similarity between two strings based on word overlap.
 * Words are lowercased and common stop words are stripped.
 * Returns a value between 0 (no overlap) and 1 (identical word sets).
 */
export function jaccardSimilarity(a, b) {
  const wordsOf = (s) => {
    const words = (s || '').toLowerCase().split(/\s+/).filter(w => w.length > 0);
    return new Set(words.filter(w => !STOP_WORDS.has(w)));
  };

  const setA = wordsOf(a);
  const setB = wordsOf(b);

  let intersection = 0;
  for (const w of setA) {
    if (setB.has(w)) intersection++;
  }

  const union = setA.size + setB.size - intersection;
  return union === 0 ? 1.0 : intersection / union;
}

/**
 * Fetch open issues and find any with titles similar to the proposed title.
 * Returns an array of { number, title, similarity } for matches above threshold.
 */
export async function findDuplicates(gh, owner, repo, title, threshold = 0.6) {
  let realIssues;
  try {
    realIssues = await paginateIssues(gh, owner, repo, {
      params: { state: 'open' },
      max: 500,
    });
  } catch (error) {
    // If we can't fetch issues, don't block proposal creation.
    console.warn(`Could not fetch issues for duplicate check: ${error.message}`);
    return [];
  }

  const matches = [];
  for (const issue of realIssues) {
    const similarity = jaccardSimilarity(title, issue.title);
    if (similarity > threshold) {
      matches.push({ number: issue.number, title: issue.title, similarity });
    }
  }

  return matches.sort((a, b) => b.similarity - a.similarity);
}

/**
 * Build the issue body. Uses structured format when Phase 4 fields are present,
 * otherwise falls back to the plain body for backward compatibility.
 */
export function buildIssueBody(idea) {
  const hasStructuredFields = idea.rationale || idea.currentState ||
    idea.proposedState || (idea.affectedFiles?.length > 0) || idea.scope;

  if (!hasStructuredFields) {
    return [
      idea.body,
      '',
      '---',
      `*Priority: ${idea.priority} — proposed by [repo-butler](https://github.com/IsmaelMartinez/repo-butler)*`,
    ].join('\n');
  }

  const sections = [];

  if (idea.rationale) {
    sections.push(`## Rationale\n${idea.rationale}`);
  }
  if (idea.currentState) {
    sections.push(`## Current State\n${idea.currentState}`);
  }
  if (idea.proposedState) {
    sections.push(`## Proposed State\n${idea.proposedState}`);
  }
  if (idea.scope) {
    sections.push(`## Scope\n${idea.scope}`);
  }
  if (idea.affectedFiles && idea.affectedFiles.length > 0) {
    const fileList = idea.affectedFiles.map(f => `- ${f}`).join('\n');
    sections.push(`## Affected Files\n${fileList}`);
  }

  sections.push('---');
  sections.push(`*Priority: ${idea.priority} — proposed by [repo-butler](https://github.com/IsmaelMartinez/repo-butler)*`);

  return sections.join('\n\n');
}

/**
 * Check if a set of labels includes the governance-declined marker.
 * Labels can be objects with .name or plain strings.
 */
export function isGovernanceDeclined(labels) {
  if (!Array.isArray(labels)) return false;
  return labels.some(l => (l.name || l) === 'governance-declined');
}

/**
 * Find open or recently closed PRs with titles similar to the proposed title.
 * Used by governance proposals to avoid re-proposing declined changes.
 */
export async function findDuplicatePRs(gh, owner, repo, title, { threshold = 0.6, includeClosedDays = 0 } = {}) {
  const matches = [];

  let openPRs;
  try {
    openPRs = await gh.paginate(`/repos/${owner}/${repo}/pulls`, {
      params: { state: 'open', per_page: 100 },
    });
  } catch {
    return [];
  }

  for (const pr of openPRs) {
    const similarity = jaccardSimilarity(title, pr.title);
    if (similarity > threshold) {
      matches.push({ number: pr.number, title: pr.title, similarity, state: 'open' });
    }
  }

  // Check recently closed PRs if requested.
  // Uses sort=updated to get most recent first, capped at 100 to avoid excessive
  // API calls on repos with thousands of PRs. The date cutoff below filters further.
  if (includeClosedDays > 0) {
    let closedPRs;
    try {
      closedPRs = await gh.paginate(`/repos/${owner}/${repo}/pulls`, {
        params: { state: 'closed', sort: 'updated', direction: 'desc', per_page: 100 },
        max: 100,
      });
    } catch {
      closedPRs = [];
    }

    const cutoff = Date.now() - includeClosedDays * 86400000;
    for (const pr of closedPRs) {
      if (!pr.closed_at || new Date(pr.closed_at).getTime() < cutoff) continue;
      const similarity = jaccardSimilarity(title, pr.title);
      if (similarity > threshold) {
        matches.push({
          number: pr.number, title: pr.title, similarity,
          state: 'closed',
          declined: isGovernanceDeclined(pr.labels || []),
        });
      }
    }
  }

  return matches.sort((a, b) => b.similarity - a.similarity);
}

// Key-presence membership for the propose-targets / propose-classes maps,
// matching the apply-schedule idiom (`name: true`). Enabled only by boolean
// true or the string 'true' (the latter tolerates a quoted YAML value); any
// other value — or absence — does not enable, so opting in stays explicit.
function isProposeEnabled(map, key) {
  const v = map?.[key];
  return v === true || v === 'true';
}

/**
 * Decide where an idea's issue is filed: the host backlog (the default and the
 * fallback) or a cross-repo target. The deterministic safety boundary is
 * resolveCrossRepoDestination (safety.js: REPO_NAME_PATTERN + statistic-bearing
 * finding anchor + eligibility + statistic rationale); the propose-targets and
 * propose-classes maps are the operator allow-list layered on top. An idea
 * crosses ONLY when the gate admits it AND its target is on propose-targets AND
 * its anchoring class is enabled in propose-classes. A malformed (injection-
 * shaped) target name is dropped outright — filed nowhere, not even on the host
 * (the G4 hard-drop contract), so it is never interpolated into a write path.
 * Everything else — no target, a gate host-fallback, or a target/class the
 * operator has not opted in — files on the host, exactly as today. With both
 * maps empty (the default) nothing crosses, so this is byte-identical to filing
 * every issue on the host.
 *
 * Returns one of:
 *   { action: 'drop',  reason }                                  — a malformed,
 *       injection-shaped target name: the idea is filed NOWHERE, not even on the
 *       host (the G4 hard-drop contract; ADR-011). Distinct from a host fallback.
 *   { action: 'file',  repo, crossRepo, anchorType?, reason }    — file on the
 *       host (crossRepo:false) or the cross-repo target (crossRepo:true).
 * `reason` is a stable code for the dry-run soak log, never an echoed adversary
 * substring. The owner is always the host owner (never config/LLM-supplied), so
 * only `repo` varies.
 */
export function resolveProposalDestination(idea, { findings = [], eligibleRepoNames = [], owner = null, hostRepo, proposeTargets = {}, proposeClasses = {} }) {
  const gate = resolveCrossRepoDestination(idea, { findings, eligibleRepoNames, owner });
  // A malformed target name is injection-shaped: the gate drops it and the idea
  // is not filed anywhere. Honoured here rather than collapsed into a host filing
  // so the documented hard-drop contract holds end-to-end.
  if (gate.destination === 'drop') {
    return { action: 'drop', reason: gate.reason };
  }
  if (gate.destination === 'cross-repo'
      && isProposeEnabled(proposeTargets, gate.repo)
      && isProposeEnabled(proposeClasses, gate.anchorType)) {
    return { action: 'file', repo: gate.repo, crossRepo: true, anchorType: gate.anchorType, reason: 'cross-repo' };
  }
  // The gate said host, or admitted cross-repo but the operator has not opted
  // this target+class in: file on the host backlog.
  const reason = gate.destination === 'cross-repo' ? 'not-allowlisted' : gate.reason;
  return { action: 'file', repo: hostRepo, crossRepo: false, reason };
}

// Thin orchestration wrapper used by the index dispatcher.
export async function runPropose(context) {
  const result = await propose(context);
  context.proposeResult = result;
  return result;
}

export async function propose(context) {
  const { owner, repo, token, ideas, config, dryRun } = context;

  if (!ideas || ideas.length === 0) {
    console.log('No ideas to propose — run IDEATE first.');
    return null;
  }

  // Safety-filter ideas before proposing.
  const safety = validateIdeas(ideas);
  if (safety.errors.length > 0) {
    console.warn(`SAFETY: ${safety.errors.length} issues found, ${ideas.length - safety.filtered.length} ideas dropped:`);
    for (const err of safety.errors) console.warn(`  - ${err}`);
  }
  if (!safety.valid) {
    console.error('SAFETY: No ideas passed validation. Skipping PROPOSE.');
    return { created: [], dropped: ideas.length, safety };
  }
  const safeIdeas = safety.filtered;

  const requireApproval = config.limits?.require_approval !== false;

  if (requireApproval && !dryRun) {
    console.log('require_approval is enabled — running in dry-run mode.');
    console.log('Set require_approval: false in .github/roadmap.yml to create issues automatically.');
    console.log('Ideas that would be proposed:');
    for (const idea of safeIdeas) {
      console.log(`  [${idea.priority}] ${idea.title}`);
    }
    return { created: [], dropped: ideas.length, require_approval: true };
  }

  const gh = context.gh || createClient(token);
  const maxIssues = config.limits?.max_issues_per_run || 3;
  // `??` (not `||`) so an explicit 0 is honoured as "file no cross-repo issues
  // this run" — a deliberate kill switch — rather than coerced back to a default;
  // absent → 1.
  const maxPerTarget = config.limits?.max_issues_per_target ?? 1;
  const proposalLabel = config.limits?.labels?.proposal || 'roadmap-proposal';
  const agentLabel = config.limits?.labels?.agent || 'agent-generated';

  // Cross-repo routing inputs (ADR-011, G5). The governance findings anchor the
  // gate; the portfolio's eligible repo names are the defence-in-depth
  // eligibility set; the two maps are the operator allow-list. All absent (e.g.
  // PROPOSE run without the upstream phases) → fail-closed to host.
  const findings = Array.isArray(context.governanceFindings) ? context.governanceFindings : [];
  const eligibleRepoNames = context.portfolio?.repos ? eligibleRepos(context.portfolio.repos).map(r => r.name) : [];
  const proposeTargets = config['propose-targets'] || {};
  const proposeClasses = config['propose-classes'] || {};

  // Ensure the proposal/agent labels exist on a repo before filing there.
  // Idempotent and memoised per repo: the host is done up front (unchanged from
  // before), and a cross-repo target is labelled lazily the first time an issue
  // actually routes to it (so an empty allow-list touches no other repo).
  const labelSpecs = [
    [proposalLabel, 'Issue proposed by repo-butler', '7057ff'],
    [agentLabel, 'Created by an automated agent', 'c5def5'],
  ];
  const labelledRepos = new Set();
  const ensureLabelsOn = async (r) => {
    if (labelledRepos.has(r)) return;
    for (const [name, desc, color] of labelSpecs) await ensureLabel(gh, owner, r, name, desc, color);
    labelledRepos.add(r);
  };
  await ensureLabelsOn(repo);

  // Sort by priority: high > medium > low.
  const priorityOrder = { high: 0, medium: 1, low: 2 };
  const sorted = [...safeIdeas].sort((a, b) =>
    (priorityOrder[a.priority] ?? 1) - (priorityOrder[b.priority] ?? 1)
  );

  const toPropose = sorted.slice(0, maxIssues);
  const created = [];
  const skippedDuplicates = [];
  const failures = [];
  // Per-target volume cap (ADR-011 two-axis cap): the per-run slice above is the
  // portfolio-wide ceiling; this Map bounds issues filed into any single
  // cross-repo target. The host is never counted here — it stays bounded only by
  // the per-run cap, so host behaviour is unchanged. The slice is applied BEFORE
  // this cap (rather than iterating all candidates) to keep empty-map behaviour
  // byte-identical; the only cost is that a target-heavy top-N can under-fill the
  // per-run budget — the safe direction (fewer issues, never more).
  const perTargetCreated = new Map();
  const skippedCapped = [];

  for (const idea of toPropose) {
    // Resolve the destination FIRST, before any repo-specific API call, so a
    // cross-repo target name is validated and allow-listed before we touch it
    // (ADR-011). With empty maps this is always the host repo.
    const dest = resolveProposalDestination(idea, { findings, eligibleRepoNames, owner, hostRepo: repo, proposeTargets, proposeClasses });

    // A malformed (injection-shaped) target name is dropped outright: filed
    // nowhere, not even on the host, and never interpolated into an API path.
    if (dest.action === 'drop') {
      console.log(`Skipping '${idea.title}' — malformed target name, idea dropped (${dest.reason}).`);
      continue;
    }
    const destRepo = dest.repo;

    // Per-target cap (ADR-011 two-axis cap): cross-repo targets only — the host
    // is bounded by the per-run cap, so this never alters host behaviour. Checked
    // before any repo-specific API call so a capped target costs no requests.
    if (dest.crossRepo && (perTargetCreated.get(destRepo) || 0) >= maxPerTarget) {
      console.log(`Skipping '${idea.title}' — per-target cap (${maxPerTarget}) reached for ${destRepo}.`);
      skippedCapped.push({ title: idea.title, repo: destRepo });
      continue;
    }

    // Duplicate detection: skip if a similar open issue already exists on the
    // destination repo.
    const duplicates = await findDuplicates(gh, owner, destRepo, idea.title);
    if (duplicates.length > 0) {
      const best = duplicates[0];
      console.log(`Skipping '${idea.title}' — similar to existing #${best.number}: '${best.title}' (similarity: ${best.similarity.toFixed(2)})`);
      skippedDuplicates.push({ title: idea.title, duplicate: best });
      continue;
    }

    // PR duplicate detection: skip if a similar open or recently declined PR exists.
    const prDuplicates = await findDuplicatePRs(gh, owner, destRepo, idea.title, { includeClosedDays: 90 });
    if (prDuplicates.length > 0) {
      const best = prDuplicates[0];
      const reason = best.declined ? 'governance-declined' : `similar ${best.state} PR`;
      console.log(`Skipping '${idea.title}' — ${reason} #${best.number}: '${best.title}' (similarity: ${best.similarity.toFixed(2)})`);
      skippedDuplicates.push({ title: idea.title, duplicate: best, reason });
      continue;
    }

    const labels = [proposalLabel, agentLabel, ...sanitizeLabels(idea.labels)];
    const body = buildIssueBody(idea);

    // validateIdeas only checks idea.body, but the composed body also embeds
    // the structured LLM fields (rationale, currentState, proposedState,
    // scope, affectedFiles). Validate the final string that actually reaches
    // GitHub so those fields pass the same gate (URLs, @mentions, keys, length).
    // Cross-repo destinations get the extra cross-reference autolink gate (G3) so
    // an owner/repo#N or bare #N can't notify or mis-link in the target repo.
    const bodyCheck = validateIssueBody(body, { crossRepo: dest.crossRepo });
    if (!bodyCheck.valid) {
      console.warn(`SAFETY: composed body for '${idea.title}' failed validation, skipping idea:`);
      for (const err of bodyCheck.errors) console.warn(`  - ${redactErrorForLog(err)}`);
      continue;
    }

    if (dryRun) {
      // Record the resolved destination for the dormant cross-repo soak: whether
      // it would cross, where to, and (for a targeted idea that does not cross)
      // why it fell back to the host.
      const tag = dest.crossRepo
        ? ` [cross-repo → ${destRepo}]`
        : (idea.targetRepo ? ` [target: ${idea.targetRepo} → host (${dest.reason})]` : '');
      console.log(`DRY RUN — would create issue${tag}: "${idea.title}" [${labels.join(', ')}]`);
      created.push({ title: idea.title, labels, targetRepo: idea.targetRepo ?? null, routedRepo: destRepo, crossRepo: dest.crossRepo, routeReason: dest.reason, url: null });
      if (dest.crossRepo) perTargetCreated.set(destRepo, (perTargetCreated.get(destRepo) || 0) + 1);
      continue;
    }

    // Labels are ensured on the destination repo only now that the gates have
    // passed (ADR-011: a cross-repo label is created on the target only after
    // admission). For the host this was already done up front, so it is a no-op.
    // Wrapped with the write below so a cross-repo target that has issues
    // disabled or is unwritable by the token fails this idea, not the whole run.
    try {
      await ensureLabelsOn(destRepo);

      const issue = await gh.request(`/repos/${owner}/${destRepo}/issues`, {
        method: 'POST',
        body: { title: idea.title, body, labels },
      });

      console.log(`Created issue #${issue.number}: ${issue.title} — ${issue.html_url}`);
      created.push({ title: idea.title, number: issue.number, labels, targetRepo: idea.targetRepo ?? null, routedRepo: destRepo, crossRepo: dest.crossRepo, routeReason: dest.reason, url: issue.html_url });
      if (dest.crossRepo) perTargetCreated.set(destRepo, (perTargetCreated.get(destRepo) || 0) + 1);
    } catch (error) {
      // A single failed write (e.g. a cross-repo target with issues disabled or
      // missing write scope) must not abort the run and block later proposals —
      // mirroring the defensive try/catch on findDuplicates/findDuplicatePRs/ensureLabel.
      console.error(`Failed to create issue for '${idea.title}' on ${destRepo}: ${redactErrorForLog(error.message)}`);
      failures.push({ title: idea.title, repo: destRepo, crossRepo: dest.crossRepo });
    }
  }

  if (toPropose.length < safeIdeas.length) {
    console.log(`Capped at ${maxIssues} issues. ${safeIdeas.length - maxIssues} ideas dropped.`);
  }

  return { created, dropped: ideas.length - created.length, skippedDuplicates, skippedCapped, failures };
}

async function ensureLabel(gh, owner, repo, name, description, color) {
  try {
    await gh.request(`/repos/${owner}/${repo}/labels/${encodeURIComponent(name)}`);
  } catch {
    try {
      await gh.request(`/repos/${owner}/${repo}/labels`, {
        method: 'POST',
        body: { name, description, color },
      });
      console.log(`Created label: ${name}`);
    } catch {
      // Label might have been created concurrently — ignore.
    }
  }
}
