// UPDATE phase: generate an updated roadmap document and open a PR.

import { createClient } from './github.js';
import { validateIssueBody, validateRoadmap, sanitizeForPrompt, wrapPrompt } from './safety.js';

const FALLBACK_PR_BODY_TAIL = 'No assessment available — roadmap updated based on current observation data.';

// Build the roadmap PR body. Optionally include the LLM-generated assessment;
// the caller is expected to validate the resulting string via validateIssueBody
// before sending it to the GitHub API.
export function buildRoadmapPrBody(assessmentText) {
  const tail = assessmentText
    ? `### Assessment\n\n${assessmentText}`
    : FALLBACK_PR_BODY_TAIL;
  return [
    '## Roadmap Update',
    '',
    'This PR was generated by [Repo Butler](https://github.com/IsmaelMartinez/repo-butler).',
    '',
    tail,
  ].join('\n');
}

const ROADMAP_BRANCH_PREFIX = 'repo-butler/roadmap-update-';

// Find an open roadmap-update PR. Returns the first match or null. Exported
// for testing. Uses the paginate helper's default cap (500) — a stale roadmap
// PR could otherwise be hidden behind 100+ unrelated PRs in busy consumer
// repos and cause the dedup to silently miss.
export async function findOpenRoadmapPr(gh, owner, repo) {
  const open = await gh.paginate(`/repos/${owner}/${repo}/pulls`, {
    params: { state: 'open' },
  });
  return open.find(pr => pr.head?.ref?.startsWith(ROADMAP_BRANCH_PREFIX)) || null;
}

// Conservative ceiling for the assessment text inside the PR body. Leaves
// headroom under safety.js's MAX_BODY_LENGTH (8000) for surrounding header
// and footer. Long-but-benign assessments are truncated rather than dropped
// — distinguishes "too verbose" from "blocked content" so operators can tell
// the false-positive from a real injection in the logs.
const MAX_ASSESSMENT_LENGTH = 6000;

// Minimum fraction of the input roadmap length the LLM output must preserve.
// PR #176 produced ~19% of the input (277 lines → 53). 80% leaves slack for
// genuine compaction (e.g. moving a few completed items to a "done" section)
// while catching destructive rewrites. Tune if false-positives appear.
const MIN_LENGTH_PRESERVATION = 0.8;

// Compare output length against input length and reject obvious rewrites.
// Empty inputs (first run, missing roadmap) are exempt — there is no prior
// document to preserve. Exported for testing.
export function checkLengthPreservation(input, output) {
  if (!input || input.length === 0) return { valid: true };
  const ratio = (output?.length || 0) / input.length;
  if (ratio < MIN_LENGTH_PRESERVATION) {
    return {
      valid: false,
      ratio,
      error: `Roadmap output length is ${(ratio * 100).toFixed(1)}% of input (${output?.length || 0}/${input.length} chars), below the ${(MIN_LENGTH_PRESERVATION * 100).toFixed(0)}% preservation threshold`,
    };
  }
  return { valid: true, ratio };
}

// Strip user-controlled content from validation error strings before they
// reach CI logs. Safety errors include the matched @mention handle, URL host,
// or other adversary-supplied substring; logging those verbatim reproduces
// the leak in a different sink. Keep the category prefix (everything up to
// the first ':') and replace the remainder with [REDACTED].
export function redactErrorForLog(err) {
  const idx = err.indexOf(':');
  if (idx === -1) return err;
  return `${err.slice(0, idx)} [REDACTED]`;
}

// Build a safety-validated PR body. If the assessment-bearing body fails
// validation (blocked URLs, @mentions, key patterns, length, etc.), fall back
// to the assessment-free body so the roadmap PR can still ship with safe text.
// Truncates over-long assessments first so verbose-but-benign output doesn't
// trigger the fallback path.
export function buildSafePrBody(assessmentText) {
  if (!assessmentText) {
    return { body: buildRoadmapPrBody(null), redacted: false, truncated: false, errors: [] };
  }

  const truncated = assessmentText.length > MAX_ASSESSMENT_LENGTH;
  const safeText = truncated ? assessmentText.slice(0, MAX_ASSESSMENT_LENGTH) : assessmentText;
  const withAssessment = buildRoadmapPrBody(safeText);

  const result = validateIssueBody(withAssessment);
  if (result.valid) return { body: withAssessment, redacted: false, truncated, errors: [] };

  return { body: buildRoadmapPrBody(null), redacted: true, truncated, errors: result.errors };
}

// Thin orchestration wrapper used by the index dispatcher. Stores the
// result on context for downstream phases / GITHUB_OUTPUT reporting.
export async function runUpdate(context) {
  const result = await update(context);
  context.updateResult = result;
  return result;
}

export async function update(context) {
  const { owner, repo, token, snapshot, assessment, provider, config, dryRun } = context;

  if (!provider) {
    console.log('No LLM provider configured — skipping UPDATE phase.');
    return null;
  }

  if (!snapshot) {
    console.log('No snapshot available — run OBSERVE first.');
    return null;
  }

  const roadmapPath = config.roadmap?.path || 'ROADMAP.md';
  const currentRoadmap = snapshot.roadmap?.content || '';

  const gh = createClient(token);

  // Idempotency: the daily pipeline runs 4×/day. Without this guard, every
  // run opens a fresh roadmap PR. If a previous run's PR is still open, treat
  // it as the authoritative draft and skip — the next run after merge/close
  // will open a new one with current state. Run before the LLM call so
  // skipped runs cost zero tokens.
  const existing = await findOpenRoadmapPr(gh, owner, repo);
  if (existing) {
    console.log(`Open roadmap PR already exists: ${existing.html_url} — skipping.`);
    return { roadmap: null, pr: existing.html_url, safety: null, deduped: true };
  }

  const prompt = buildUpdatePrompt(currentRoadmap, snapshot, assessment, config.context);
  const updatedRoadmap = await provider.generate(prompt);

  // Length-preservation guard: PR #176 exposed that the LLM will happily
  // rewrite a 277-line roadmap down to 53 lines, deleting SHIPPED records
  // and Future entries. Treat any output that drops below 80% of the input
  // length as a destructive rewrite and refuse the PR. Symmetric with the
  // validateRoadmap safety check below.
  const preservation = checkLengthPreservation(currentRoadmap, updatedRoadmap);
  if (!preservation.valid) {
    console.error(`SAFETY: ${preservation.error} — refusing PR (suspected destructive rewrite).`);
    // Log the actual LLM output (head + tail) so the soak can diagnose why the
    // model produced a destructive rewrite. Without this the guard is opaque —
    // we know the output was too short, but not what it contained.
    const head = (updatedRoadmap || '').slice(0, 800);
    const tail = (updatedRoadmap || '').length > 1600 ? (updatedRoadmap || '').slice(-800) : '';
    console.error(`SAFETY: rejected output head:\n${head}`);
    if (tail) console.error(`SAFETY: rejected output tail:\n${tail}`);
    return { roadmap: updatedRoadmap, pr: null, safety: { valid: false, errors: [preservation.error] } };
  }

  // Safety check before publishing.
  const safety = validateRoadmap(updatedRoadmap);
  if (!safety.valid) {
    console.error('SAFETY: Roadmap failed validation, skipping PR creation:');
    for (const err of safety.errors) console.error(`  - ${err}`);
    return { roadmap: updatedRoadmap, pr: null, safety };
  }

  if (dryRun) {
    console.log('DRY RUN — would create PR with updated roadmap (safety: passed).');
    console.log('Updated roadmap preview (first 500 chars):');
    console.log(updatedRoadmap.slice(0, 500));
    return { roadmap: updatedRoadmap, pr: null, safety };
  }

  const branchName = `${ROADMAP_BRANCH_PREFIX}${Date.now()}`;
  const defaultBranch = snapshot.meta?.default_branch || 'main';

  // Create branch from default branch.
  const ref = await gh.request(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`);
  await gh.request(`/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    body: { ref: `refs/heads/${branchName}`, sha: ref.object.sha },
  });

  // Get current file SHA if it exists.
  let fileSha;
  try {
    const existing = await gh.request(`/repos/${owner}/${repo}/contents/${roadmapPath}`, {
      params: { ref: defaultBranch },
    });
    fileSha = existing.sha;
  } catch {
    // File doesn't exist yet.
  }

  // Write updated roadmap to the branch.
  await gh.request(`/repos/${owner}/${repo}/contents/${roadmapPath}`, {
    method: 'PUT',
    body: {
      message: `chore: update roadmap (repo-butler)`,
      content: Buffer.from(updatedRoadmap).toString('base64'),
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {}),
    },
  });

  // Build the PR body, validating any LLM-supplied assessment text. The
  // assessment text reaches GitHub directly, so it must pass the same safety
  // checks as any other LLM output (blocked URLs, @mentions, API keys, …).
  const { body: prBody, redacted, truncated, errors: bodyErrors } = buildSafePrBody(assessment?.assessment);
  if (truncated && !redacted) {
    console.log(`SAFETY: Assessment truncated to ${6000} chars before validation (verbose but benign).`);
  }
  if (redacted) {
    console.warn('SAFETY: Roadmap PR body assessment failed validation, using safe fallback body:');
    // Redact user-controlled content from each error string before logging
    // (otherwise an @mention or URL host blocked here would just leak into CI logs).
    for (const err of bodyErrors) console.warn(`  - ${redactErrorForLog(err)}`);
  }

  // Create PR.
  const pr = await gh.request(`/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    body: {
      title: 'chore: update roadmap (repo-butler)',
      head: branchName,
      base: defaultBranch,
      body: prBody,
    },
  });

  console.log(`PR created: ${pr.html_url}`);
  return { roadmap: updatedRoadmap, pr: pr.html_url, safety };
}

export function buildUpdatePrompt(currentRoadmap, snapshot, assessment, projectContext, now = new Date()) {
  // Inject today's date as a literal so the LLM never has to guess it from
  // its training cutoff. PR #176 hallucinated `Last Updated: 2024-07-20`.
  const today = now.toISOString().slice(0, 10);
  const items = [
    `Today: ${today}`,
    `Repository: ${snapshot.repository}`,
    `Current version: ${snapshot.package?.version || snapshot.summary.latest_release || 'unknown'}`,
    `Open issues: ${snapshot.summary.open_issues}`,
    `Blocked: ${snapshot.summary.blocked_issues}`,
    `Awaiting feedback: ${snapshot.summary.awaiting_feedback}`,
    `PRs merged (90d): ${snapshot.summary.recently_merged_prs}`,
    '',
  ];

  if (assessment?.assessment) {
    items.push('Recent assessment:', sanitizeForPrompt(assessment.assessment), '');
  }

  if (assessment?.diff?.new_issues?.length > 0) {
    items.push('New issues since last update:');
    for (const i of assessment.diff.new_issues.slice(0, 15)) {
      items.push(`  #${i.number}: ${sanitizeForPrompt(i.title)} [${i.labels.join(', ')}]`);
    }
    items.push('');
  }

  if (assessment?.diff?.resolved_issues?.length > 0) {
    items.push('Resolved issues:');
    for (const i of assessment.diff.resolved_issues.slice(0, 15)) {
      items.push(`  #${i.number}: ${sanitizeForPrompt(i.title)}`);
    }
    items.push('');
  }

  if (assessment?.diff?.new_releases?.length > 0) {
    items.push('New releases:');
    for (const r of assessment.diff.new_releases) {
      items.push(`  ${r.tag} (${r.published_at?.split('T')[0]})`);
    }
    items.push('');
  }

  items.push('High-reaction issues:', ...(snapshot.summary.high_reaction_issues.map(i => `  ${sanitizeForPrompt(i)}`)), '');
  items.push('Top labels:', ...(snapshot.summary.top_open_labels.map(l => `  ${l}`)), '');

  if (currentRoadmap) {
    items.push('--- CURRENT ROADMAP ---', sanitizeForPrompt(currentRoadmap), '--- END CURRENT ROADMAP ---', '');
  }

  return wrapPrompt({
    role: 'You are an editor maintaining an existing roadmap document for an open-source project. Apply the smallest set of edits to the roadmap below to reflect the current project state. The roadmap is the project history; preserve it.',
    projectContext,
    items,
    outroLines: [
      'Instructions:',
      '- Make the smallest set of changes needed. Do not delete or summarise existing SHIPPED records, completed entries, ADR references, or section headings.',
      '- Append new entries; do not rewrite old ones. If a section already exists, add to it rather than replacing it.',
      '- Update status markers, version numbers, and the "Last Updated" line. Use the literal date provided above ("Today: …") — do not guess or use a different date.',
      '- Add new items only for newly opened issues that represent significant work. Do not invent new sections.',
      '- Preserve the original structure, tone, headings, and approximate length. The output must be at least as long as the input minus minor compaction.',
      '- Output ONLY the updated roadmap document, no commentary, no explanation.',
    ],
  });
}
