// UPDATE phase: generate an updated roadmap document and open a PR.

import { createClient } from './github.js';
import { validateRoadmap } from './safety.js';

export async function update(context) {
  const { owner, repo, token, snapshot, assessment, provider, config, dryRun } = context;

  if (!provider) {
    console.log('No LLM provider configured — skipping UPDATE phase.');
    return null;
  }

  if (!snapshot) {
    console.log('No snapshot available — run OBSERVE first.');
    return null;
  }

  const roadmapPath = config.roadmap?.path || 'ROADMAP.md';
  const currentRoadmap = snapshot.roadmap?.content || '';

  const prompt = buildUpdatePrompt(currentRoadmap, snapshot, assessment, config.context);
  const updatedRoadmap = await provider.generate(prompt);

  // Safety check before publishing.
  const safety = validateRoadmap(updatedRoadmap);
  if (!safety.valid) {
    console.error('SAFETY: Roadmap failed validation, skipping PR creation:');
    for (const err of safety.errors) console.error(`  - ${err}`);
    return { roadmap: updatedRoadmap, pr: null, safety };
  }

  if (dryRun) {
    console.log('DRY RUN — would create PR with updated roadmap (safety: passed).');
    console.log('Updated roadmap preview (first 500 chars):');
    console.log(updatedRoadmap.slice(0, 500));
    return { roadmap: updatedRoadmap, pr: null, safety };
  }

  const gh = createClient(token);
  const branchName = `repo-butler/roadmap-update-${Date.now()}`;
  const defaultBranch = snapshot.meta?.default_branch || 'main';

  // Create branch from default branch.
  const ref = await gh.request(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`);
  await gh.request(`/repos/${owner}/${repo}/git/refs`, {
    method: 'POST',
    body: { ref: `refs/heads/${branchName}`, sha: ref.object.sha },
  });

  // Get current file SHA if it exists.
  let fileSha;
  try {
    const existing = await gh.request(`/repos/${owner}/${repo}/contents/${roadmapPath}`, {
      params: { ref: defaultBranch },
    });
    fileSha = existing.sha;
  } catch {
    // File doesn't exist yet.
  }

  // Write updated roadmap to the branch.
  await gh.request(`/repos/${owner}/${repo}/contents/${roadmapPath}`, {
    method: 'PUT',
    body: {
      message: `chore: update roadmap (repo-butler)`,
      content: Buffer.from(updatedRoadmap).toString('base64'),
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {}),
    },
  });

  // Create PR.
  const pr = await gh.request(`/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    body: {
      title: 'chore: update roadmap (repo-butler)',
      head: branchName,
      base: defaultBranch,
      body: [
        '## Roadmap Update',
        '',
        'This PR was generated by [Repo Butler](https://github.com/IsmaelMartinez/repo-butler).',
        '',
        assessment?.assessment
          ? `### Assessment\n\n${assessment.assessment}`
          : 'No assessment available — roadmap updated based on current observation data.',
      ].join('\n'),
    },
  });

  console.log(`PR created: ${pr.html_url}`);
  return { roadmap: updatedRoadmap, pr: pr.html_url };
}

function buildUpdatePrompt(currentRoadmap, snapshot, assessment, projectContext) {
  const parts = [
    'You are a roadmap writer for an open-source project. Update the roadmap document below based on the current project state.',
    '',
    projectContext ? `Project context: ${projectContext}` : '',
    '',
    `Repository: ${snapshot.repository}`,
    `Current version: ${snapshot.package?.version || snapshot.summary.latest_release || 'unknown'}`,
    `Open issues: ${snapshot.summary.open_issues}`,
    `Blocked: ${snapshot.summary.blocked_issues}`,
    `Awaiting feedback: ${snapshot.summary.awaiting_feedback}`,
    `PRs merged (90d): ${snapshot.summary.recently_merged_prs}`,
    '',
  ];

  if (assessment?.assessment) {
    parts.push('Recent assessment:', assessment.assessment, '');
  }

  if (assessment?.diff?.new_issues?.length > 0) {
    parts.push('New issues since last update:');
    for (const i of assessment.diff.new_issues.slice(0, 15)) {
      parts.push(`  #${i.number}: ${i.title} [${i.labels.join(', ')}]`);
    }
    parts.push('');
  }

  if (assessment?.diff?.resolved_issues?.length > 0) {
    parts.push('Resolved issues:');
    for (const i of assessment.diff.resolved_issues.slice(0, 15)) {
      parts.push(`  #${i.number}: ${i.title}`);
    }
    parts.push('');
  }

  if (assessment?.diff?.new_releases?.length > 0) {
    parts.push('New releases:');
    for (const r of assessment.diff.new_releases) {
      parts.push(`  ${r.tag} (${r.published_at?.split('T')[0]})`);
    }
    parts.push('');
  }

  parts.push('High-reaction issues:', ...(snapshot.summary.high_reaction_issues.map(i => `  ${i}`)), '');
  parts.push('Top labels:', ...(snapshot.summary.top_open_labels.map(l => `  ${l}`)), '');

  if (currentRoadmap) {
    parts.push('--- CURRENT ROADMAP ---', currentRoadmap, '--- END CURRENT ROADMAP ---', '');
  }

  parts.push('Instructions:');
  parts.push('- Update the roadmap to reflect the current state. Keep the same structure and tone.');
  parts.push('- Move completed items to a "done" section if applicable.');
  parts.push('- Add new items for newly opened issues that represent significant work.');
  parts.push('- Update version numbers, dates, and status markers.');
  parts.push('- Be concise — the roadmap should be scannable, not verbose.');
  parts.push('- Output ONLY the updated roadmap document, no commentary.');

  return parts.join('\n');
}
