// UPDATE phase: generate an updated roadmap document and open a PR.

import { createClient } from './github.js';
import { validateIssueBody, validateRoadmap, sanitizeForPrompt, wrapPrompt } from './safety.js';

const FALLBACK_PR_BODY_TAIL = 'No assessment available — roadmap updated based on current observation data.';

// The roadmap sections the LLM may append new entries to. Shared by the prompt
// builder (which advertises them) and applyEditOps (which validates against
// them and recovers ops where the model put a section name in the action
// field). Exported for testing.
export const SECTION_NAMES = ['Implemented', 'Next Up', 'Future'];

// Build the roadmap PR body. Optionally include the LLM-generated assessment;
// the caller is expected to validate the resulting string via validateIssueBody
// before sending it to the GitHub API.
export function buildRoadmapPrBody(assessmentText) {
  const tail = assessmentText
    ? `### Assessment\n\n${assessmentText}`
    : FALLBACK_PR_BODY_TAIL;
  return [
    '## Roadmap Update',
    '',
    'This PR was generated by [Repo Butler](https://github.com/IsmaelMartinez/repo-butler).',
    '',
    tail,
  ].join('\n');
}

const ROADMAP_BRANCH_PREFIX = 'repo-butler/roadmap-update-';

// Find an open roadmap-update PR. Returns the first match or null. Exported
// for testing. Uses the paginate helper's default cap (500) — a stale roadmap
// PR could otherwise be hidden behind 100+ unrelated PRs in busy consumer
// repos and cause the dedup to silently miss.
export async function findOpenRoadmapPr(gh, owner, repo) {
  const open = await gh.paginate(`/repos/${owner}/${repo}/pulls`, {
    params: { state: 'open' },
  });
  return open.find(pr => pr.head?.ref?.startsWith(ROADMAP_BRANCH_PREFIX)) || null;
}

// Conservative ceiling for the assessment text inside the PR body. Leaves
// headroom under safety.js's MAX_BODY_LENGTH (8000) for surrounding header
// and footer. Long-but-benign assessments are truncated rather than dropped
// — distinguishes "too verbose" from "blocked content" so operators can tell
// the false-positive from a real injection in the logs.
const MAX_ASSESSMENT_LENGTH = 6000;

// Minimum fraction of the input roadmap length the LLM output must preserve.
// PR #176 produced ~19% of the input (277 lines → 53). 80% leaves slack for
// genuine compaction (e.g. moving a few completed items to a "done" section)
// while catching destructive rewrites. Tune if false-positives appear.
const MIN_LENGTH_PRESERVATION = 0.8;

// Compare output length against input length and reject obvious rewrites.
// Empty inputs (first run, missing roadmap) are exempt — there is no prior
// document to preserve. Exported for testing.
export function checkLengthPreservation(input, output) {
  if (!input || input.length === 0) return { valid: true };
  const ratio = (output?.length || 0) / input.length;
  if (ratio < MIN_LENGTH_PRESERVATION) {
    return {
      valid: false,
      ratio,
      error: `Roadmap output length is ${(ratio * 100).toFixed(1)}% of input (${output?.length || 0}/${input.length} chars), below the ${(MIN_LENGTH_PRESERVATION * 100).toFixed(0)}% preservation threshold`,
    };
  }
  return { valid: true, ratio };
}

// Count `~~...~~` strikethrough markers in markdown text. Greedy/single-line
// only — multi-line strikethrough isn't a convention this roadmap uses, and
// allowing newlines inside would over-match across paragraphs.
function countStrikethrough(text) {
  return (text?.match(/~~[^~\n]+~~/g) || []).length;
}

// Refuse output that drops any `~~strikethrough~~` markers in place. PR #202
// stripped 24 strikethroughs from SHIPPED headings under the 80% length guard
// because the diff was balanced (+38/-40). Strikethrough is the load-bearing
// visual convention for completed work; an edit-only prompt should never have
// a reason to lower the count. Empty inputs exempt (first run). Output count
// can be ≥ input count to allow newly-shipped entries getting their marker.
export function checkStrikethroughPreservation(input, output) {
  if (!input || input.length === 0) return { valid: true };
  const inputCount = countStrikethrough(input);
  const outputCount = countStrikethrough(output || '');
  if (outputCount < inputCount) {
    return {
      valid: false,
      inputCount,
      outputCount,
      error: `Strikethrough marker count dropped from ${inputCount} to ${outputCount} — output stripped ${inputCount - outputCount} ~~...~~ markers from existing SHIPPED entries`,
    };
  }
  return { valid: true, inputCount, outputCount };
}

// Extract every `#NN` PR/issue reference token from markdown text. Matches the
// number-with-hash form regardless of surrounding context — `(PR #84)`, `PR
// #176`, `PRs #23–#37`, `issue #211`, and bare `#202` all yield the numeric
// ID. Returns a Set so duplicates collapse and order doesn't matter.
function extractIssueRefs(text) {
  return new Set((text?.match(/#\d+\b/g) || []));
}

// Refuse output that drops any PR or issue reference present in the input.
// PR #213 deleted the `License concern severity tuned 2026-04-04 (PR #84)`
// paragraph under both the 80% length guard and the strikethrough-count
// guard — the paragraph carried no `~~...~~` markup and barely moved the
// length needle. The `#NN` reference is the narrowest invariant that catches
// this: every input PR/issue reference must survive in the output, and the
// LLM has no legitimate edit-only reason to drop one. Output can be a
// superset (new entries get their own refs); only missing input refs fail.
export function checkPrReferencePreservation(input, output) {
  const inputRefs = extractIssueRefs(input);
  const outputRefs = extractIssueRefs(output);
  const missing = [...inputRefs].filter(r => !outputRefs.has(r));
  if (missing.length > 0) {
    // Cap the surfaced list so a catastrophic deletion doesn't log a thousand
    // refs; the head plus a count carries enough signal to investigate.
    const head = missing.slice(0, 10).join(', ');
    const overflow = missing.length > 10 ? ` (and ${missing.length - 10} more)` : '';
    return {
      valid: false,
      inputCount: inputRefs.size,
      outputCount: outputRefs.size,
      missing,
      error: `Dropped ${missing.length} PR/issue reference(s) from existing roadmap entries: ${head}${overflow}`,
    };
  }
  return { valid: true, inputCount: inputRefs.size, outputCount: outputRefs.size, missing: [] };
}

// Strip user-controlled content from validation error strings before they
// reach CI logs. Safety errors include the matched @mention handle, URL host,
// or other adversary-supplied substring; logging those verbatim reproduces
// the leak in a different sink. Keep the category prefix (everything up to
// the first ':') and replace the remainder with [REDACTED].
export function redactErrorForLog(err) {
  const idx = err.indexOf(':');
  if (idx === -1) return err;
  return `${err.slice(0, idx)} [REDACTED]`;
}

// Build a safety-validated PR body. If the assessment-bearing body fails
// validation (blocked URLs, @mentions, key patterns, length, etc.), fall back
// to the assessment-free body so the roadmap PR can still ship with safe text.
// Truncates over-long assessments first so verbose-but-benign output doesn't
// trigger the fallback path.
export function buildSafePrBody(assessmentText) {
  if (!assessmentText) {
    return { body: buildRoadmapPrBody(null), redacted: false, truncated: false, errors: [] };
  }

  const truncated = assessmentText.length > MAX_ASSESSMENT_LENGTH;
  const safeText = truncated ? assessmentText.slice(0, MAX_ASSESSMENT_LENGTH) : assessmentText;
  const withAssessment = buildRoadmapPrBody(safeText);

  const result = validateIssueBody(withAssessment);
  if (result.valid) return { body: withAssessment, redacted: false, truncated, errors: [] };

  return { body: buildRoadmapPrBody(null), redacted: true, truncated, errors: result.errors };
}

// Thin orchestration wrapper used by the index dispatcher. Stores the
// result on context for downstream phases / GITHUB_OUTPUT reporting.
export async function runUpdate(context) {
  const result = await update(context);
  context.updateResult = result;
  return result;
}

export async function update(context) {
  const { owner, repo, token, snapshot, assessment, provider, config, dryRun } = context;

  if (!provider) {
    console.log('No LLM provider configured — skipping UPDATE phase.');
    return null;
  }

  if (!snapshot) {
    console.log('No snapshot available — run OBSERVE first.');
    return null;
  }

  const roadmapPath = config.roadmap?.path || 'ROADMAP.md';
  const currentRoadmap = snapshot.roadmap?.content || '';

  const gh = createClient(token);

  // Idempotency: the daily pipeline runs 4×/day. If a previous run's PR is
  // still open, refresh its branch with the latest output rather than open a
  // duplicate (or — as before this change — skip and produce no soak signal).
  // PR #202 stayed open from 2026-05-08 → 2026-05-11 and silenced 12 cron
  // ticks of soak data because the skip path returned early before the LLM
  // call. Refreshing means every tick produces an updated preview the soak
  // can spot-check, and the unchanged-content guard below prevents spurious
  // no-op commits on the existing branch.
  const existing = await findOpenRoadmapPr(gh, owner, repo);
  const isRefresh = !!existing;

  const today = new Date().toISOString().slice(0, 10);
  const prompt = buildSectionEditPrompt(currentRoadmap, snapshot, assessment, config.context);
  const rawResponse = await provider.generate(prompt);

  const parsed = parseEditOps(rawResponse);
  if (!parsed.valid) {
    console.error(`SECTION-EDIT: failed to parse LLM response — ${parsed.error}`);
    console.error(`SECTION-EDIT: raw response (first 500 chars): ${(rawResponse || '').slice(0, 500)}`);
    return { roadmap: currentRoadmap, pr: null, safety: { valid: false, errors: [parsed.error] } };
  }

  const { result: updatedRoadmap, applied, skipped } = applyEditOps(currentRoadmap, parsed.ops, today);
  console.log(`SECTION-EDIT: ${applied.length} ops applied, ${skipped.length} skipped.`);
  for (const op of applied) console.log(`  applied: ${op}`);
  for (const op of skipped) console.warn(`  skipped: ${op}`);

  if (updatedRoadmap === currentRoadmap) {
    console.log('SECTION-EDIT: no changes after applying ops — skipping PR.');
    return { roadmap: updatedRoadmap, pr: null, safety: { valid: true, errors: [] } };
  }

  // Defence-in-depth: the section-edit approach is additive-only, so these
  // guards should always pass. Keep them to catch bugs in applyEditOps.
  const safety = validateRoadmap(updatedRoadmap);
  if (!safety.valid) {
    console.error('SAFETY: Roadmap failed validation after applying ops:');
    for (const err of safety.errors) console.error(`  - ${redactErrorForLog(err)}`);
    return { roadmap: updatedRoadmap, pr: null, safety };
  }

  if (dryRun) {
    console.log('DRY RUN — all guards passed, would create PR with updated roadmap.');
    return { roadmap: updatedRoadmap, pr: null, safety };
  }

  const defaultBranch = snapshot.meta?.default_branch || 'main';
  const branchName = isRefresh ? existing.head.ref : `${ROADMAP_BRANCH_PREFIX}${Date.now()}`;

  // Create the branch only when opening a new PR. On refresh we reuse the
  // existing PR's head ref.
  if (!isRefresh) {
    const ref = await gh.request(`/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`);
    await gh.request(`/repos/${owner}/${repo}/git/refs`, {
      method: 'POST',
      body: { ref: `refs/heads/${branchName}`, sha: ref.object.sha },
    });
  }

  // Read the current roadmap from whichever branch we're about to write to.
  // For new PRs that's the default branch (we just forked from it); for a
  // refresh that's the existing PR's branch (it may have diverged from main).
  let fileSha;
  let existingContent = null;
  try {
    const f = await gh.request(`/repos/${owner}/${repo}/contents/${roadmapPath}`, {
      params: { ref: branchName },
    });
    fileSha = f.sha;
    existingContent = Buffer.from(f.content, 'base64').toString('utf8');
  } catch {
    // File doesn't exist on this branch.
  }

  // No-op short-circuit: if the new output matches what's already on the
  // refresh branch, skip the commit + PR PATCH to avoid spurious churn.
  if (isRefresh && existingContent === updatedRoadmap) {
    console.log(`Roadmap unchanged from existing PR ${existing.html_url} — skipping refresh push.`);
    return { roadmap: updatedRoadmap, pr: existing.html_url, safety, refreshed: false };
  }

  // Write updated roadmap to the branch.
  await gh.request(`/repos/${owner}/${repo}/contents/${roadmapPath}`, {
    method: 'PUT',
    body: {
      message: isRefresh ? 'chore: refresh roadmap update (repo-butler)' : 'chore: update roadmap (repo-butler)',
      content: Buffer.from(updatedRoadmap).toString('base64'),
      branch: branchName,
      ...(fileSha ? { sha: fileSha } : {}),
    },
  });

  // Build the PR body, validating any LLM-supplied assessment text. The
  // assessment text reaches GitHub directly, so it must pass the same safety
  // checks as any other LLM output (blocked URLs, @mentions, API keys, …).
  const { body: prBody, redacted, truncated, errors: bodyErrors } = buildSafePrBody(assessment?.assessment);
  if (truncated && !redacted) {
    console.log(`SAFETY: Assessment truncated to ${6000} chars before validation (verbose but benign).`);
  }
  if (redacted) {
    console.warn('SAFETY: Roadmap PR body assessment failed validation, using safe fallback body:');
    // Redact user-controlled content from each error string before logging
    // (otherwise an @mention or URL host blocked here would just leak into CI logs).
    for (const err of bodyErrors) console.warn(`  - ${redactErrorForLog(err)}`);
  }

  if (isRefresh) {
    // Update the existing PR's body so the Assessment text reflects the
    // current run; the diff itself updates automatically because the head
    // branch moved with the PUT above.
    await gh.request(`/repos/${owner}/${repo}/pulls/${existing.number}`, {
      method: 'PATCH',
      body: { body: prBody },
    });
    console.log(`Refreshed existing roadmap PR ${existing.html_url}`);
    return { roadmap: updatedRoadmap, pr: existing.html_url, safety, refreshed: true };
  }

  // Create new PR.
  const pr = await gh.request(`/repos/${owner}/${repo}/pulls`, {
    method: 'POST',
    body: {
      title: 'chore: update roadmap (repo-butler)',
      head: branchName,
      base: defaultBranch,
      body: prBody,
    },
  });

  console.log(`PR created: ${pr.html_url}`);
  return { roadmap: updatedRoadmap, pr: pr.html_url, safety };
}

// Parse the LLM response as a JSON array of edit operations. Strips markdown
// code fences if present. Exported for testing.
export function parseEditOps(text) {
  if (!text) return { valid: false, error: 'Empty response', ops: [] };
  const stripped = text.replace(/^```(?:json)?\n?/m, '').replace(/\n?```\s*$/m, '').trim();
  try {
    const ops = JSON.parse(stripped);
    if (!Array.isArray(ops)) return { valid: false, error: 'Response is not a JSON array', ops: [] };
    return { valid: true, ops };
  } catch (e) {
    return { valid: false, error: `Invalid JSON: ${e.message}`, ops: [] };
  }
}

// Find the insertion point (character index) for appending to a section.
// Inserts before the next `---` or `## ` boundary after the section heading.
function findSectionInsertPoint(roadmap, sectionName) {
  const regex = new RegExp(`^## ${sectionName.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\b`, 'm');
  const match = roadmap.match(regex);
  if (!match) return -1;

  const afterHeading = match.index + match[0].length;
  const rest = roadmap.slice(afterHeading);
  const boundary = rest.match(/\n(?=---\s*\n|## )/);
  return boundary ? afterHeading + boundary.index : roadmap.length;
}

// Recover a recurring LLM malformation before classification: the model puts
// the section name directly in the `action` field (e.g.
// {"action":"Implemented","text":"…"}) instead of the documented
// {"action":"append","section":"Implemented","text":"…"}. The live pipeline
// dropped two such ops on 2026-05-29 as "unknown action: Implemented",
// silently losing genuinely-new Implemented entries. When `action` is itself a
// valid section name, reinterpret the op as an append to that section — an
// explicit valid `section` field still wins if present. Genuinely unknown
// actions (e.g. "delete") are returned untouched and still skipped downstream,
// preserving the additive-only guarantee. Exported for testing.
export function normalizeEditOp(op) {
  if (!op || typeof op !== 'object') return op;

  // Canonicalize a section name to its exact SECTION_NAMES casing. LLMs drift
  // ("implemented", "next up"), and findSectionInsertPoint matches the heading
  // case-sensitively — so a drifted-case section would silently fail to insert.
  // Returns undefined when the name is not a known section.
  const canonical = (name) =>
    typeof name === 'string'
      ? SECTION_NAMES.find(s => s.toLowerCase() === name.toLowerCase())
      : undefined;

  // Section-name-in-the-action-field malformation: reinterpret as an append to
  // that section. An explicit valid `section` field still wins if present.
  if (op.action && op.action !== 'append') {
    const fromAction = canonical(op.action);
    if (fromAction) {
      return { ...op, action: 'append', section: canonical(op.section) || fromAction };
    }
  }

  // Well-formed append with a drifted-case section: normalize so the
  // case-sensitive findSectionInsertPoint can locate the heading.
  if (op.action === 'append') {
    const c = canonical(op.section);
    if (c && c !== op.section) return { ...op, section: c };
  }

  return op;
}

// Apply edit operations to the roadmap deterministically. Only additive
// operations are supported — the LLM cannot delete or rewrite content.
// Exported for testing.
export function applyEditOps(roadmap, ops, today) {
  let result = roadmap;
  const applied = [];
  const skipped = [];

  // Always update the date line deterministically.
  const dateReplaced = result.replace(
    /(\*\*Last Updated:\*\*)\s*\d{4}-\d{2}-\d{2}/,
    `$1 ${today}`,
  );
  if (dateReplaced !== result) {
    result = dateReplaced;
    applied.push(`update_date → ${today}`);
  }

  for (const rawOp of ops) {
    const op = normalizeEditOp(rawOp);
    if (!op || !op.action) {
      skipped.push('invalid op (missing action)');
      continue;
    }

    if (op.action === 'append') {
      const section = op.section;
      const text = op.text?.trim();
      if (!section || !text) {
        skipped.push(`append: missing section or text`);
        continue;
      }
      const insertAt = findSectionInsertPoint(result, section);
      if (insertAt === -1) {
        skipped.push(`append: section "${section}" not found`);
        continue;
      }
      result = result.slice(0, insertAt) + '\n\n' + text + result.slice(insertAt);
      applied.push(`append to "${section}" (${text.length} chars)`);
    } else {
      skipped.push(`unknown action: ${op.action}`);
    }
  }

  return { result, applied, skipped };
}

export function buildSectionEditPrompt(currentRoadmap, snapshot, assessment, projectContext, now = new Date()) {
  const today = now.toISOString().slice(0, 10);
  const items = [
    `Today: ${today}`,
    `Repository: ${snapshot.repository}`,
    `Current version: ${snapshot.package?.version || snapshot.summary.latest_release || 'unknown'}`,
    `Open issues: ${snapshot.summary.open_issues}`,
    `Blocked: ${snapshot.summary.blocked_issues}`,
    `Awaiting feedback: ${snapshot.summary.awaiting_feedback}`,
    `PRs merged (90d): ${snapshot.summary.recently_merged_prs}`,
    '',
  ];

  if (assessment?.assessment) {
    items.push('Recent assessment:', sanitizeForPrompt(assessment.assessment), '');
  }

  if (assessment?.diff?.new_issues?.length > 0) {
    items.push('New issues since last update:');
    for (const i of assessment.diff.new_issues.slice(0, 15)) {
      items.push(`  #${i.number}: ${sanitizeForPrompt(i.title)} [${i.labels.join(', ')}]`);
    }
    items.push('');
  }

  if (assessment?.diff?.resolved_issues?.length > 0) {
    items.push('Resolved issues:');
    for (const i of assessment.diff.resolved_issues.slice(0, 15)) {
      items.push(`  #${i.number}: ${sanitizeForPrompt(i.title)}`);
    }
    items.push('');
  }

  if (assessment?.diff?.new_releases?.length > 0) {
    items.push('New releases:');
    for (const r of assessment.diff.new_releases) {
      items.push(`  ${r.tag} (${r.published_at?.split('T')[0]})`);
    }
    items.push('');
  }

  items.push('High-reaction issues:', ...(snapshot.summary.high_reaction_issues.map(i => `  ${sanitizeForPrompt(i)}`)), '');
  items.push('Top labels:', ...(snapshot.summary.top_open_labels.map(l => `  ${l}`)), '');

  if (currentRoadmap) {
    items.push('--- CURRENT ROADMAP (read-only context, do NOT reproduce) ---', sanitizeForPrompt(currentRoadmap), '--- END CURRENT ROADMAP ---', '');
  }

  return wrapPrompt({
    role: 'You decide what NEW entries to append to a project roadmap. You do NOT reproduce or edit the existing document — the code handles that. You only output a JSON array of operations.',
    projectContext,
    items,
    outroLines: [
      'Instructions:',
      `- Output a JSON array of append operations. Each operation: {"action": "append", "section": "<name>", "text": "<paragraph>"}`,
      '- The "action" field is ALWAYS the literal string "append". The section name goes in the "section" field, never in "action".',
      `  Wrong: {"action": "Implemented", "text": "…"}`,
      `  Correct: {"action": "append", "section": "Implemented", "text": "…"}`,
      `- Valid section names (for the "section" field): ${SECTION_NAMES.map(s => `"${s}"`).join(', ')}. No other section names are accepted.`,
      '- Only create entries for genuinely new work visible in the data above (new merged PRs, resolved issues, new releases).',
      '- Do not repeat or summarise anything already in the roadmap. Read the current roadmap carefully before deciding.',
      '- If nothing meaningful changed since the last update, return an empty array: []',
      '- Each "text" value should be a single markdown paragraph in the style of existing entries (e.g. "Feature X shipped 2026-05-26 (PR #N). Description of what changed.").',
      '- Do not invent PR numbers, issue numbers, or dates not present in the data above.',
      '- Output ONLY the JSON array, no commentary, no markdown fences, no explanation.',
    ],
  });
}

// Legacy prompt kept for reference but no longer called by update().
export function buildUpdatePrompt(currentRoadmap, snapshot, assessment, projectContext, now = new Date()) {
  // Inject today's date as a literal so the LLM never has to guess it from
  // its training cutoff. PR #176 hallucinated `Last Updated: 2024-07-20`.
  const today = now.toISOString().slice(0, 10);
  const items = [
    `Today: ${today}`,
    `Repository: ${snapshot.repository}`,
    `Current version: ${snapshot.package?.version || snapshot.summary.latest_release || 'unknown'}`,
    `Open issues: ${snapshot.summary.open_issues}`,
    `Blocked: ${snapshot.summary.blocked_issues}`,
    `Awaiting feedback: ${snapshot.summary.awaiting_feedback}`,
    `PRs merged (90d): ${snapshot.summary.recently_merged_prs}`,
    '',
  ];

  if (assessment?.assessment) {
    items.push('Recent assessment:', sanitizeForPrompt(assessment.assessment), '');
  }

  if (assessment?.diff?.new_issues?.length > 0) {
    items.push('New issues since last update:');
    for (const i of assessment.diff.new_issues.slice(0, 15)) {
      items.push(`  #${i.number}: ${sanitizeForPrompt(i.title)} [${i.labels.join(', ')}]`);
    }
    items.push('');
  }

  if (assessment?.diff?.resolved_issues?.length > 0) {
    items.push('Resolved issues:');
    for (const i of assessment.diff.resolved_issues.slice(0, 15)) {
      items.push(`  #${i.number}: ${sanitizeForPrompt(i.title)}`);
    }
    items.push('');
  }

  if (assessment?.diff?.new_releases?.length > 0) {
    items.push('New releases:');
    for (const r of assessment.diff.new_releases) {
      items.push(`  ${r.tag} (${r.published_at?.split('T')[0]})`);
    }
    items.push('');
  }

  items.push('High-reaction issues:', ...(snapshot.summary.high_reaction_issues.map(i => `  ${sanitizeForPrompt(i)}`)), '');
  items.push('Top labels:', ...(snapshot.summary.top_open_labels.map(l => `  ${l}`)), '');

  if (currentRoadmap) {
    items.push('--- CURRENT ROADMAP ---', sanitizeForPrompt(currentRoadmap), '--- END CURRENT ROADMAP ---', '');
  }

  return wrapPrompt({
    role: 'You are an editor maintaining an existing roadmap document for an open-source project. Apply the smallest set of edits to the roadmap below to reflect the current project state. The roadmap is the project history; preserve it.',
    projectContext,
    items,
    outroLines: [
      'Instructions:',
      '- Make the smallest set of changes needed. The only allowed changes are: updating the "Last Updated" date, updating status markers, and appending new entries at the end of the appropriate section.',
      '- VERBATIM RULE: every existing paragraph must appear in the output with IDENTICAL wording, in the SAME position (except for allowed updates to status markers and the "Last Updated" date). Do not rephrase, reword, move, reorder, or summarise any existing text. Copy it character-for-character. This is the most important rule.',
      '- Do not delete any paragraph, sentence, or entry — even if it seems minor, outdated, or tangential. The roadmap is a historical record.',
      '- Append new entries at the end of the relevant section. Do not insert them between existing entries or rewrite old ones.',
      '- Update the "Last Updated" line to the date provided above ("Today: …"). Do not change any other dates.',
      '- Do not invent new sections or new entries for PRs not listed in the data above.',
      '- Preserve `~~strikethrough~~` markers verbatim. Do not strip `~~...~~` from any heading or inline marker. This rule is non-negotiable.',
      '  Wrong: `### Phase 1 — Richer Observation SHIPPED`',
      '  Correct: `### ~~Phase 1 — Richer Observation~~ SHIPPED`',
      '- Preserve every `#NN` PR or issue reference present in the input. This rule is non-negotiable.',
      '- Output ONLY the updated roadmap document, no commentary, no explanation.',
    ],
  });
}
